#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh
$HOME/styli.sh/styli.sh -n -s "mountains" -w 1366 -h 768

bspc monitor -d I II III IV V VI VII

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true



bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a spotify desktop='^3' follow=on
bspc rule -a telegram-desktop desktop='^4' follow=on
bspc rule -a vlc desktop='^5' state=floating follow=on
bspc rule -a pcmanfm desktop='^6' state=floating follow=on
